version: '3'
services:
  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    tty: true
    ports:
      - "3000:3000"
      - "20002:20002"
    volumes:
      - ./:/nuxt
    container_name: nuxt_amplify
